config/routes.rb
Rails.application.routes.draw do
  
  
  resources :genres
  get "movies/filter/:filter" => "movies#index", as: :filtered_movies
  root "movies#index"
  
  resources :movies do
    resources :reviews
    resources :favorites, only: [:create, :destroy]
  end

  resources :users
  get "signup" => "users#new"

  resource :session, only: [:new, :create, :destroy]
  get "signin" => "sessions#new"

end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
    <%= content_tag(:div, message, class: "flash #{type}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
    <p>
    Copyright &copy; 2005-<%= Time.now.year %>
    <%= link_to 'Zach Koek Github', 'https://github.com/zach-koek'%>
    </p>
     
</footer>

app/views/layouts/_header.html.erb
  <header>
  <nav>
    <%= link_to(image_tag("logo.png"), root_path) %>
    <ul class="left">
      <li>
        <div> <%= link_to("Released", movies_path) %></div>
      </li>
      <li>
        <div> <%= link_to("Recent", filtered_movies_path(:recent)) %></div>
      </li>
      <li>
        <div> <%= link_to("Upcoming", filtered_movies_path(:upcoming)) %></div>
      </li>
    </ul>
    <ul class="right">
      <% if session[:user_id]%>
        <li>
          <%= link_to current_user.name, current_user %>
        </li>
         <li>
          <%= link_to "Sign Out", session_url, method: :delete, class: "button" %>
        </li>
      <% else %>
        <li>
          <%= link_to "Sign Up", signup_path, class: "button" %>
        <li>
        <li>
          <%= link_to "Sign In", signin_path, class: "button" %>
        <li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Koek Flix</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/header' %>

    <div class="content"> 
      <%= render 'layouts/flash' %>
      <%= yield %> 
    </div>

    <%= render 'layouts/footer' %>




  </body>
</html>